{
 "title": "Discord Bot",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hourly Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(commands_total[1h]))",
     "legendFormat": "commands"
    },
    {
     "expr": "sum(increase(errors_total[1h]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Daily Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(commands_total[1d]))",
     "legendFormat": "commands"
    },
    {
     "expr": "sum(increase(errors_total[1d]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Error Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(errors_total) / (sum(commands_total) + sum(errors_total))) * 100",
     "legendFormat": "percentage"
    }
   ]
  },
  {
   "title": "Total Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum(commands_total)", "legendFormat": "commands" },
    { "expr": "sum(errors_total)", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Top Cogs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (cog) (commands_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Commands",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (command) (commands_total))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}